"""File Generated by Sideko (sideko.dev)"""

from teachable_public_api.core import (
    AsyncBaseClient,
    RequestOptions,
    default_request_options,
    SyncBaseClient,
)
from teachable_public_api.resources.v1.courses.lectures.quizzes import (
    AsyncQuizzesClient,
    QuizzesClient,
)
from teachable_public_api.resources.v1.courses.lectures.videos import (
    AsyncVideosClient,
    VideosClient,
)
from teachable_public_api.resources.v1.courses.lectures.mark_complete import (
    MarkCompleteClient,
    AsyncMarkCompleteClient,
)
import typing
from teachable_public_api.types.v1.courses.lectures import models


class LecturesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.quizzes = QuizzesClient(base_client=self._base_client)
        self.videos = VideosClient(base_client=self._base_client)
        self.mark_complete = MarkCompleteClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        course_id: int,
        lecture_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.LectureResponse:
        """
        Fetch content of a specific course lecture.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}",
            auth_names=["ApiKeyAuth"],
            cast_to=models.LectureResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncLecturesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.quizzes = AsyncQuizzesClient(base_client=self._base_client)
        self.videos = AsyncVideosClient(base_client=self._base_client)
        self.mark_complete = AsyncMarkCompleteClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        course_id: int,
        lecture_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.LectureResponse:
        """
        Fetch content of a specific course lecture.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}",
            auth_names=["ApiKeyAuth"],
            cast_to=models.LectureResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
