"""File Generated by Sideko (sideko.dev)"""

import io
import typing

import typing_extensions
import pydantic

ModelFiles = typing.List[
    typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]
]


class VideoAsset(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    content_type: str = pydantic.Field(alias="content_type")
    url: str = pydantic.Field(alias="url")


class VideoResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    id: int = pydantic.Field(alias="id")
    media_duration: int = pydantic.Field(alias="media_duration")
    media_type: str = pydantic.Field(alias="media_type")
    status: typing_extensions.Literal[
        "READY", "PROCESSING", "PARTIALLY_READY", "QUEUED", "THUMBNAIL_READY", "FAILED"
    ] = pydantic.Field(alias="status")
    url_thumbnail: str = pydantic.Field(alias="url_thumbnail")
    video_asset: VideoAsset = pydantic.Field(alias="video_asset")


class GetV1CoursesCourseIdLecturesLectureIdVideosVideoIdResponse(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        populate_by_name=True,
    )

    video: VideoResponse = pydantic.Field(alias="video")
