"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class UpdateUserRequest(typing_extensions.TypedDict):
    """
    No description specified
    """

    name: typing_extensions.NotRequired[str]
    src: typing_extensions.NotRequired[str]


class _SerializerUpdateUserRequest(pydantic.BaseModel):
    """
    Serializer for UpdateUserRequest handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    name: typing.Optional[str] = pydantic.Field(alias="name", default=None)
    src: typing.Optional[str] = pydantic.Field(alias="src", default=None)


class CreateUserRequest(typing_extensions.TypedDict):
    """
    No description specified
    """

    email_field: typing_extensions.Required[str]
    name: typing_extensions.NotRequired[str]
    password: typing_extensions.NotRequired[str]
    src: typing_extensions.NotRequired[str]


class _SerializerCreateUserRequest(pydantic.BaseModel):
    """
    Serializer for CreateUserRequest handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    email_field: str = pydantic.Field(alias="email")
    name: typing.Optional[str] = pydantic.Field(alias="name", default=None)
    password: typing.Optional[str] = pydantic.Field(alias="password", default=None)
    src: typing.Optional[str] = pydantic.Field(alias="src", default=None)
