"""File Generated by Sideko (sideko.dev)"""

from teachable_public_api.core import (
    RequestOptions,
    to_encodable,
    SyncBaseClient,
    AsyncBaseClient,
    default_request_options,
)
from teachable_public_api.types.v1.enroll import params
import typing


class EnrollClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.Enrollment,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Enroll a user in a course.
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerEnrollment)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/v1/enroll",
            auth_names=["ApiKeyAuth"],
            json=_json,
            cast_to=type(None),
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncEnrollClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.Enrollment,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Enroll a user in a course.
        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerEnrollment)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/v1/enroll",
            auth_names=["ApiKeyAuth"],
            json=_json,
            cast_to=type(None),
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
