"""File Generated by Sideko (sideko.dev)"""

from teachable_public_api.core import (
    SyncBaseClient,
    default_request_options,
    AsyncBaseClient,
    RequestOptions,
)
import typing
from teachable_public_api.types.v1.courses.lectures.quizzes.responses import models


class ResponsesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def list(
        self,
        *,
        course_id: int,
        lecture_id: int,
        quiz_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizResponse:
        """
        Fetch the responses of quiz.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes/{quiz_id}/responses",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncResponsesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def list(
        self,
        *,
        course_id: int,
        lecture_id: int,
        quiz_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizResponse:
        """
        Fetch the responses of quiz.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes/{quiz_id}/responses",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
