"""File Generated by Sideko (sideko.dev)"""

from teachable_public_api.core import (
    RequestOptions,
    default_request_options,
    AsyncBaseClient,
    SyncBaseClient,
)
from teachable_public_api.resources.v1.courses.lectures.quizzes.responses import (
    AsyncResponsesClient,
    ResponsesClient,
)
import typing
from teachable_public_api.types.v1.courses.lectures.quizzes import models


class QuizzesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.responses = ResponsesClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def get(
        self,
        *,
        course_id: int,
        lecture_id: int,
        quiz_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizInformationResponse:
        """
        Fetch a specific quiz information.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes/{quiz_id}",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizInformationResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def list(
        self,
        *,
        course_id: int,
        lecture_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizzesResponse:
        """
        Fetch an id list of quizzes in a specific course lecture.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizzesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncQuizzesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.responses = AsyncResponsesClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def get(
        self,
        *,
        course_id: int,
        lecture_id: int,
        quiz_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizInformationResponse:
        """
        Fetch a specific quiz information.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes/{quiz_id}",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizInformationResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def list(
        self,
        *,
        course_id: int,
        lecture_id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.QuizzesResponse:
        """
        Fetch an id list of quizzes in a specific course lecture.
        """
        # start -- build request data (keep comment for code generation)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/v1/courses/{course_id}/lectures/{lecture_id}/quizzes",
            auth_names=["ApiKeyAuth"],
            cast_to=models.QuizzesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
