"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class Enrollment(typing_extensions.TypedDict):
    """
    No description specified
    """

    course_id: typing_extensions.Required[int]
    user_id: typing_extensions.Required[int]


class _SerializerEnrollment(pydantic.BaseModel):
    """
    Serializer for Enrollment handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    course_id: int = pydantic.Field(alias="course_id")
    user_id: int = pydantic.Field(alias="user_id")
