"""File Generated by Sideko (sideko.dev)"""

from teachable_public_api.core import SyncBaseClient, AsyncBaseClient
from teachable_public_api.resources.v1.courses import CoursesClient, AsyncCoursesClient
from teachable_public_api.resources.v1.pricing_plans import (
    AsyncPricingPlansClient,
    PricingPlansClient,
)
from teachable_public_api.resources.v1.transactions import (
    AsyncTransactionsClient,
    TransactionsClient,
)
from teachable_public_api.resources.v1.users import UsersClient, AsyncUsersClient
from teachable_public_api.resources.v1.webhooks import (
    WebhooksClient,
    AsyncWebhooksClient,
)
from teachable_public_api.resources.v1.enroll import AsyncEnrollClient, EnrollClient
from teachable_public_api.resources.v1.unenroll import (
    UnenrollClient,
    AsyncUnenrollClient,
)


class V1Client:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.courses = CoursesClient(base_client=self._base_client)
        self.pricing_plans = PricingPlansClient(base_client=self._base_client)
        self.transactions = TransactionsClient(base_client=self._base_client)
        self.users = UsersClient(base_client=self._base_client)
        self.webhooks = WebhooksClient(base_client=self._base_client)
        self.enroll = EnrollClient(base_client=self._base_client)
        self.unenroll = UnenrollClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncV1Client:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.courses = AsyncCoursesClient(base_client=self._base_client)
        self.pricing_plans = AsyncPricingPlansClient(base_client=self._base_client)
        self.transactions = AsyncTransactionsClient(base_client=self._base_client)
        self.users = AsyncUsersClient(base_client=self._base_client)
        self.webhooks = AsyncWebhooksClient(base_client=self._base_client)
        self.enroll = AsyncEnrollClient(base_client=self._base_client)
        self.unenroll = AsyncUnenrollClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
